### ISSUE TITLE
elm-aws-core status question

### ISSUE THREAD

**Issue by billstclair** [ktonon/elm-aws-core#1]
I tried sending this as an email, but it bounced. Feel free to delete this issue once you've seen it, as it isn't really an issue. Reply here or to billstclair@gmail.com. Thanks.

-----

Kevin,

I would like to have an S3 backend for my https://github.com/billstclair/xossbow project, a pure Elm blogging package which encodes Elm user interfaces in JSON and Markdown, and relies on only the ability to write a text file to the backend, no backend code at all other than that.

My investigation led me to your elm-crypto, elm-aws-core, and elm-aws-generate respositories. I was hoping to be able to use elm-aws-generate to make the S3 module, but S3 has a unique signature and protocol, which is not yet supported by elm-aws-generate, as you probably already know.

I have not yet started building any S3 code on top of elm-aws-core. I have so far only (successfully) run elm-test on it. But before I do that, I’d like to know if you think it’s ready for that, or if I will have to make extensive changes before it’s likely to work. I’m also wondering if you have an estimated date for publishing it on package.elm-lang.org. I realize that it’s a spare time labor of love for you (as is Xossbow for me), so I don’t expect anything.

Thank you for your attention.

Bill St. Clair
billstclair@gmail.com

P.S. Your Elm code is gorgeous!

**Comment by ktonon** [comment]
Hey @billstclair,

sorry about the delayed response. I'm having issues with that old email address, I've updated my github account to use my other email.

As for the status of this repo, you are right that it doesn't support V2 signing for requests to S3. However, all regions [should now support V4 signing](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html), so its possible that it could work with a few changes.

* there is an exception to the construction of [canonical](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) requests for s3, and this is [not yet accounted for](https://github.com/ktonon/elm-aws-core/blob/master/src/AWS/Core/Signers/Canonical.elm#L36).
* I think there might be some work related to multipart uploads
* the [rest-xml protocol](https://github.com/aws/aws-sdk-js/blob/master/apis/s3-2006-03-01.normal.json) is not implemented

I don't have an estimate date for publishing this yet. I was hoping to publish a 1.0.0 release with full support for at least one protocol, along side a service library that could be used to validate it. S3 could be that service library.

You're right about the labor of love part. Unfortunately I'm not going to have much time to work on this in the near future. Collaboration is welcome!

Kevin

**Comment by billstclair** [comment]
Thanks, Kevin.

I'll be attempting to make it work for S3 sometime fairly soon. I, too, am busy with my paying work.

Bill
